# Generated by Django 2.2.2 on 2019-06-17 05:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70)),
                ('main_category', models.CharField(choices=[('VEH', 'Vehicles'), ('PRO', 'Properties'), ('MOB&Acc', 'Mobile Phones & Accessories'), ('ELE&HOAPP', 'Electronics & Home Appliances'), ('HO&GA', 'Home & Garden'), ('FAS&BEA', 'Fashion & Beauty'), ('PET', 'Pets'), ('Kid', 'Kids & Babies'), ('SPORT', 'Sporting Goods & Bikes'), ('HOB', 'Hobbies, Music, Art & Books'), ('JOB', 'Jobs'), ('BUSS', 'Business & Industrial'), ('SER', 'Services')], max_length=50)),
                ('description', models.TextField()),
                ('photos', models.FileField(upload_to='Images/%Y-%m-%d/')),
                ('city', models.CharField(max_length=120)),
                ('Mobile_phone_number', models.CharField(max_length=11)),
                ('create_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
