# Generated by Django 2.2.2 on 2019-06-18 08:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='advertisement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=70)),
                ('adv_type', models.CharField(choices=[(0, 'cars'), (1, 'real estates'), (2, 'mobiles'), (3, 'electronics'), (4, 'house'), (5, 'fashion'), (6, 'animals'), (7, 'baby staff'), (8, 'music'), (9, 'jobs'), (10, 'trade'), (11, 'services')], max_length=3)),
                ('desc', models.TextField(max_length=8069)),
                ('name', models.TextField()),
                ('city', models.TextField(max_length=30)),
                ('mob', models.TextField(max_length=12)),
                ('email', models.EmailField(max_length=254)),
                ('connectby', models.CharField(choices=[(0, 'both'), (1, 'mob'), (2, 'olx email')], max_length=2)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='media/')),
                ('advertisement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advertisements.advertisement')),
            ],
        ),
    ]
