# Generated by Django 2.2.2 on 2019-06-18 20:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0002_auto_20190618_2024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='adv_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advertisements.AdvTypes'),
        ),
        migrations.AlterField(
            model_name='images',
            name='advertisement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advertisements.Advertisement'),
        ),
    ]
