# Generated by Django 2.2.2 on 2019-06-19 05:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0004_auto_20190618_2152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='adv_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advertisements.AdvTypes'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='connectby',
            field=models.CharField(choices=[(0, 'both'), (1, 'mob'), (2, 'olx email')], default=0, max_length=3),
        ),
        migrations.AlterField(
            model_name='images',
            name='advertisement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advertisements.Advertisement'),
        ),
    ]
