# Generated by Django 2.2.2 on 2019-06-19 07:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0005_auto_20190619_0507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='adv_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advertisements.AdvTypes'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='connectby',
            field=models.CharField(choices=[(1, 'both'), (2, 'mob'), (3, 'olx email')], default=1, max_length=3),
        ),
        migrations.AlterField(
            model_name='images',
            name='advertisement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advertisements.Advertisement'),
        ),
    ]
