# Generated by Django 2.2.2 on 2019-06-24 07:35

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0013_auto_20190623_2030'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='adv_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advertisements.AdvTypes'),
        ),
        migrations.AlterField(
            model_name='images',
            name='advertisement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advertisements.Advertisement'),
        ),
    ]
